RegexBuilder and some sample code
ermay12/17-480-regex pull request #12
Opened 2020-04-26 15:45 UTC by CalLavicka

2020-04-26 17:29 UTC, ermay12 approved these changes
Merge as is.  Any changes that I want to make i'll put up as a pull request

2020-04-26 17:47 UTC, melodeeli98 requested changes
Can we make these tests junit tests and rename the files to eg NameTest.java?

2020-04-26 22:46 UTC, melodeeli98 approved these changes

2020-04-27 18:05 UTC, merged

2020-04-27 18:06 UTC, ermay12 commented
Can you merge master into this and then merge?