Best-faith implementation of Erics ideas
ermay12/17-480-regex pull request #17
Opened 2020-04-29 02:41 UTC by alex-stanescu

Should close #13 
Related to #16

2020-05-05 20:37 UTC, ermay12 commented
see pr #18  for my thoughts

2020-05-06 21:02 UTC, CalLavicka requested changes

2020-05-06 21:02 UTC, CalLavicka commented on src/main/java/com/github/ermay12/regex/Regex.java
> +      case '|':
This should be defined as a static array/set of characters, and then checking if c is in that set. That would be more readable

2020-05-07 00:26 UTC, alex-stanescu commented on src/main/java/com/github/ermay12/regex/Regex.java
> +      case '|':
Done

2020-05-07 02:10 UTC, CalLavicka approved these changes

2020-05-07 02:12 UTC, melodeeli98 approved these changes

2020-05-07 02:12 UTC, merged